//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAFC24_Teamkits_Editor_WinForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAFC24_Teamkits_Editor_WinForms.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to armbandtype.
        /// </summary>
        internal static string armbandtype {
            get {
                return ResourceManager.GetString("armbandtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Başarıyla_kaydedildi_ {
            get {
                return ResourceManager.GetString("Başarıyla kaydedildi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to captainarmband.
        /// </summary>
        internal static string captainarmband {
            get {
                return ResourceManager.GetString("captainarmband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chestbadge.
        /// </summary>
        internal static string chestbadge {
            get {
                return ResourceManager.GetString("chestbadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Color_1_ {
            get {
                return ResourceManager.GetString("Color(1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Color_2_ {
            get {
                return ResourceManager.GetString("Color(2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Color_3_ {
            get {
                return ResourceManager.GetString("Color(3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dlc.
        /// </summary>
        internal static string dlc {
            get {
                return ResourceManager.GetString("dlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string exportkit {
            get {
                return ResourceManager.GetString("exportkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasadvertisingkit.
        /// </summary>
        internal static string hasadvertisingkit {
            get {
                return ResourceManager.GetString("hasadvertisingkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hata {
            get {
                return ResourceManager.GetString("Hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string importkit {
            get {
                return ResourceManager.GetString("importkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isembargoed.
        /// </summary>
        internal static string isembargoed {
            get {
                return ResourceManager.GetString("isembargoed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isinheritbasedetailmap.
        /// </summary>
        internal static string isinheritbasedetailmap {
            get {
                return ResourceManager.GetString("isinheritbasedetailmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to islocked.
        /// </summary>
        internal static string islocked {
            get {
                return ResourceManager.GetString("islocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseybacknamefontcase.
        /// </summary>
        internal static string jerseybacknamefontcase {
            get {
                return ResourceManager.GetString("jerseybacknamefontcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseybacknameplacementcode.
        /// </summary>
        internal static string jerseybacknameplacementcode {
            get {
                return ResourceManager.GetString("jerseybacknameplacementcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseycollargeometrytype.
        /// </summary>
        internal static string jerseycollargeometrytype {
            get {
                return ResourceManager.GetString("jerseycollargeometrytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseyfit.
        /// </summary>
        internal static string jerseyfit {
            get {
                return ResourceManager.GetString("jerseyfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseyfrontnumberplacementcode.
        /// </summary>
        internal static string jerseyfrontnumberplacementcode {
            get {
                return ResourceManager.GetString("jerseyfrontnumberplacementcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseyleftsleevebadge.
        /// </summary>
        internal static string jerseyleftsleevebadge {
            get {
                return ResourceManager.GetString("jerseyleftsleevebadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynamecolorb.
        /// </summary>
        internal static string jerseynamecolorb {
            get {
                return ResourceManager.GetString("jerseynamecolorb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynamecolorg.
        /// </summary>
        internal static string jerseynamecolorg {
            get {
                return ResourceManager.GetString("jerseynamecolorg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynamecolorr.
        /// </summary>
        internal static string jerseynamecolorr {
            get {
                return ResourceManager.GetString("jerseynamecolorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynamefonttype.
        /// </summary>
        internal static string jerseynamefonttype {
            get {
                return ResourceManager.GetString("jerseynamefonttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynamelayouttype.
        /// </summary>
        internal static string jerseynamelayouttype {
            get {
                return ResourceManager.GetString("jerseynamelayouttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorprimb.
        /// </summary>
        internal static string jerseynumbercolorprimb {
            get {
                return ResourceManager.GetString("jerseynumbercolorprimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorprimg.
        /// </summary>
        internal static string jerseynumbercolorprimg {
            get {
                return ResourceManager.GetString("jerseynumbercolorprimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorprimr.
        /// </summary>
        internal static string jerseynumbercolorprimr {
            get {
                return ResourceManager.GetString("jerseynumbercolorprimr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorsecb.
        /// </summary>
        internal static string jerseynumbercolorsecb {
            get {
                return ResourceManager.GetString("jerseynumbercolorsecb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorsecg.
        /// </summary>
        internal static string jerseynumbercolorsecg {
            get {
                return ResourceManager.GetString("jerseynumbercolorsecg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorsecr.
        /// </summary>
        internal static string jerseynumbercolorsecr {
            get {
                return ResourceManager.GetString("jerseynumbercolorsecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorterb.
        /// </summary>
        internal static string jerseynumbercolorterb {
            get {
                return ResourceManager.GetString("jerseynumbercolorterb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorterg.
        /// </summary>
        internal static string jerseynumbercolorterg {
            get {
                return ResourceManager.GetString("jerseynumbercolorterg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseynumbercolorterr.
        /// </summary>
        internal static string jerseynumbercolorterr {
            get {
                return ResourceManager.GetString("jerseynumbercolorterr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseyrenderingdetailmaptype.
        /// </summary>
        internal static string jerseyrenderingdetailmaptype {
            get {
                return ResourceManager.GetString("jerseyrenderingdetailmaptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseyrestriction.
        /// </summary>
        internal static string jerseyrestriction {
            get {
                return ResourceManager.GetString("jerseyrestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseyrightsleevebadge.
        /// </summary>
        internal static string jerseyrightsleevebadge {
            get {
                return ResourceManager.GetString("jerseyrightsleevebadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerseyshapestyle.
        /// </summary>
        internal static string jerseyshapestyle {
            get {
                return ResourceManager.GetString("jerseyshapestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit details.
        /// </summary>
        internal static string Kit_details {
            get {
                return ResourceManager.GetString("Kit details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit name.
        /// </summary>
        internal static string Kit_name {
            get {
                return ResourceManager.GetString("Kit name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit number.
        /// </summary>
        internal static string Kit_number {
            get {
                return ResourceManager.GetString("Kit number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Lütfen_dosya_seçin {
            get {
                return ResourceManager.GetString("Lütfen dosya seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Lütfen_isim_girin {
            get {
                return ResourceManager.GetString("Lütfen isim girin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Lütfen_teamkits_dosyası_açın {
            get {
                return ResourceManager.GetString("Lütfen teamkits dosyası açın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newteam.
        /// </summary>
        internal static string newteam {
            get {
                return ResourceManager.GetString("newteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numberfonttype.
        /// </summary>
        internal static string numberfonttype {
            get {
                return ResourceManager.GetString("numberfonttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powid.
        /// </summary>
        internal static string powid {
            get {
                return ResourceManager.GetString("powid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renderingmaterialtype.
        /// </summary>
        internal static string renderingmaterialtype {
            get {
                return ResourceManager.GetString("renderingmaterialtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorts number.
        /// </summary>
        internal static string Shorts_number {
            get {
                return ResourceManager.GetString("Shorts number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorprimb.
        /// </summary>
        internal static string shortsnumbercolorprimb {
            get {
                return ResourceManager.GetString("shortsnumbercolorprimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorprimg.
        /// </summary>
        internal static string shortsnumbercolorprimg {
            get {
                return ResourceManager.GetString("shortsnumbercolorprimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorprimr.
        /// </summary>
        internal static string shortsnumbercolorprimr {
            get {
                return ResourceManager.GetString("shortsnumbercolorprimr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorsecb.
        /// </summary>
        internal static string shortsnumbercolorsecb {
            get {
                return ResourceManager.GetString("shortsnumbercolorsecb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorsecg.
        /// </summary>
        internal static string shortsnumbercolorsecg {
            get {
                return ResourceManager.GetString("shortsnumbercolorsecg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorsecr.
        /// </summary>
        internal static string shortsnumbercolorsecr {
            get {
                return ResourceManager.GetString("shortsnumbercolorsecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorterb.
        /// </summary>
        internal static string shortsnumbercolorterb {
            get {
                return ResourceManager.GetString("shortsnumbercolorterb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorterg.
        /// </summary>
        internal static string shortsnumbercolorterg {
            get {
                return ResourceManager.GetString("shortsnumbercolorterg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumbercolorterr.
        /// </summary>
        internal static string shortsnumbercolorterr {
            get {
                return ResourceManager.GetString("shortsnumbercolorterr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumberfonttype.
        /// </summary>
        internal static string shortsnumberfonttype {
            get {
                return ResourceManager.GetString("shortsnumberfonttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsnumberplacementcode.
        /// </summary>
        internal static string shortsnumberplacementcode {
            get {
                return ResourceManager.GetString("shortsnumberplacementcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortsrenderingdetailmaptype.
        /// </summary>
        internal static string shortsrenderingdetailmaptype {
            get {
                return ResourceManager.GetString("shortsrenderingdetailmaptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortstyle.
        /// </summary>
        internal static string shortstyle {
            get {
                return ResourceManager.GetString("shortstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamadded.
        /// </summary>
        internal static string teamadded {
            get {
                return ResourceManager.GetString("teamadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorprimb.
        /// </summary>
        internal static string teamcolorprimb {
            get {
                return ResourceManager.GetString("teamcolorprimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorprimg.
        /// </summary>
        internal static string teamcolorprimg {
            get {
                return ResourceManager.GetString("teamcolorprimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorprimpercent.
        /// </summary>
        internal static string teamcolorprimpercent {
            get {
                return ResourceManager.GetString("teamcolorprimpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorprimr.
        /// </summary>
        internal static string teamcolorprimr {
            get {
                return ResourceManager.GetString("teamcolorprimr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorsecb.
        /// </summary>
        internal static string teamcolorsecb {
            get {
                return ResourceManager.GetString("teamcolorsecb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorsecg.
        /// </summary>
        internal static string teamcolorsecg {
            get {
                return ResourceManager.GetString("teamcolorsecg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorsecpercent.
        /// </summary>
        internal static string teamcolorsecpercent {
            get {
                return ResourceManager.GetString("teamcolorsecpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolorsecr.
        /// </summary>
        internal static string teamcolorsecr {
            get {
                return ResourceManager.GetString("teamcolorsecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolortertb.
        /// </summary>
        internal static string teamcolortertb {
            get {
                return ResourceManager.GetString("teamcolortertb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolortertg.
        /// </summary>
        internal static string teamcolortertg {
            get {
                return ResourceManager.GetString("teamcolortertg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolortertpercent.
        /// </summary>
        internal static string teamcolortertpercent {
            get {
                return ResourceManager.GetString("teamcolortertpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamcolortertr.
        /// </summary>
        internal static string teamcolortertr {
            get {
                return ResourceManager.GetString("teamcolortertr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamexist.
        /// </summary>
        internal static string teamexist {
            get {
                return ResourceManager.GetString("teamexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamkitid.
        /// </summary>
        internal static string teamkitid {
            get {
                return ResourceManager.GetString("teamkitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamkittypetechid.
        /// </summary>
        internal static string teamkittypetechid {
            get {
                return ResourceManager.GetString("teamkittypetechid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamtechid.
        /// </summary>
        internal static string teamtechid {
            get {
                return ResourceManager.GetString("teamtechid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
